name: Super-Linter

on:
  push:
    branches:
      - main

jobs:
  super-linter:
    name: Run Super-Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}